### ISSUE TITLE
Errors in neovim when showing nerdtree

### ISSUE THREAD

**Issue by mhartington** [tiagofumo/vim-nerdtree-syntax-highlight#1]
When I toggle nerdtree, I get a error message pointing to the `after/syntax/nerdtree.vim` file.

```viml
Error detected while processing /Users/mhartington/.config/nvim/.dein/after/syntax/nerdtree.vim:
line  358:
W18: Invalid character in group name
line  363:
W18: Invalid character in group name
line  358:
W18: Invalid character in group name
line  363:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
line  397:
W18: Invalid character in group name
line  390:
W18: Invalid character in group name
```

Though it does seem to be working.

![screen shot 2016-06-13 at 9 28 04 am](https://cloud.githubusercontent.com/assets/2835826/16009103/44825c5c-3149-11e6-9c45-0a85b99f06ec.png)

**Comment by mhartington** [comment]
![screen shot 2016-06-13 at 9 38 06 am](https://cloud.githubusercontent.com/assets/2835826/16009407/916bc39a-314a-11e6-8305-762f6aa842c7.png)

**Comment by tiagofumo** [comment]
hmm, the error happened in another plugin? 'dein'? Does adding v.n.s.h after all the other plugins change anything?

**Comment by mhartington** [comment]
dein is my plugin manager, it's just loading the file.

Right now, I do have it as the last plugin listed in my config, right after vim-devicons.

**Comment by tiagofumo** [comment]
oh yes, dein by shougo, a friend told me about it. Sorry, I forgot.

I think I know where the problem is, could you paste here any custom icon you added to vim-devicons and custom coloring on v.n.s.h from your .vimrc please?

**Comment by mhartington** [comment]
No custom icons or custom colors. Everything is default

**Comment by tiagofumo** [comment]
It says the error occur on line 358, but line 358 is inside a for loop of a variable declared on the same file containing all the default extensions, which means it will run for me the same way it will run for you, no matter which files you have on your project's folder. And that raises me no error apparently.

The only way I see that raising an error would be with custom characters added on you .vimrc or directly on the "nerdtree.vim" file, that is why I asked before. But you said you didn't, and that makes it really hard to track where the error comes from.

The last thing I can think of is:
1 - try opening nvim on an empty folder (so that nerdtree has no files) and tell me if any error occurs. If no errors happen, send me a .zip of a project folder where the errors happen.
2 - send me your .vimrc so I can try replicate your plugin instalation on a vagrant VM

**Comment by mhartington** [comment]
1) error happens in an empty folder 
2) init.vim is up on GH (https://github.com/mhartington/dotfiles/blob/master/config/nvim/init.vim)
Might need to removed a few plugins here and there.

**Comment by tiagofumo** [comment]
The error happens because it doesn't accept special characters in front of nerdtree syntax match statements (like '...c++', '...f#', etc), but it still works for all the files, including those with special characters on the extensions. I don't know why that gives a error message for you but I was able to replicate it using your .vimrc on a VM with vagrant. 

So i just added a silent in front of the statements to avoid the error messages. If you open the fileColorTest folder on the project's folder you can see that any extension with special characters will be highlighted.

Let me know if that worked...

**Comment by mhartington** [comment]
Working now!
