### ISSUE TITLE
How can i highlight only the Opened folder icons?

### ISSUE THREAD

**Issue by hrqmonteiro** [tiagofumo/vim-nerdtree-syntax-highlight#44]
How can i set a highlight for the Closed folders and another to the Open folders?

I tried setting: 

```
hi WebDevIconsDefaultFolderSymbol ctermfg=1 ctermbg=8 cterm=none
hi DevIconsDefaultFolderOpenSynbol ctermfg=4 ctermbg=8 cterm=none
```

But the Opened and the Closed folders are all red (color 1). What am i doing wrong?

**Comment by tiagofumo** [comment]
Have you tried using this setting from vim-devicons?
```vim
let g:DevIconsEnableFoldersOpenClose = 1
```
It adds a different icon for open and closed folders, which might be a good solution for what you want:

![img](https://i.imgur.com/3NnKfVk.png)

I just added a new identifier to open folders. You can set the colors like this on your .vimrc:
```vim
let s:red = "AE403F"
let s:blue = "689FB6"

let g:DevIconsEnableFoldersOpenClose = 1
let g:WebDevIconsDefaultFolderSymbolColor = s:red
let g:WebDevIconsDefaultOpenFolderSymbolColor= s:blue
```
Which will give you this:

![img](https://i.imgur.com/VBKuROd.png)

**Comment by hrqmonteiro** [comment]
Nice! Now it is working! Thanks!

Just one more doubt, why can't i use this when the symbols for the opened and closed folders are the same? I set them to be the same but it shows all blue?

I wanted to use the same symbol for the open and closed folders but the colors i want it different, but is not working when i change them to be the same symbol..

**Comment by tiagofumo** [comment]
So the problem is that the icons are just unicode characters. I believe the only way to highlight a character is with a syntax identifier. You create these syntax ids using regular expressions. So the problem is when the open and close characters are the same, I don't know a way to assign that to a different syntax id. There is an arrow at the beginning of the every folder line that points down when it's an open folder and points to the right for a closed folder. But I don't know how to make a regular expression that uses this as a way to apply different syntax in vim without breaking anything else.
