### ISSUE TITLE
Plugin not working properly

### ISSUE THREAD

**Issue by carlosala** [tiagofumo/vim-nerdtree-syntax-highlight#46]
Hi!

I have a problem with the plugin. I'm using `ryanoasis/vim-devicons` plugin, and a patched Nerd Font with the plugin. Although icons are not shown properly as in the screenshots in my Nerdtree on neovim. For instance, `.css` is shown as a `#`, .html as a `<>`, etc. I attach my config and some screenshots.
Thanks!
```
let g:NERDTreeHighlightFolders = 1
let g:NERDTreeHighlightFoldersFullName = 1

call plug#begin('~/.config/nvim/plugged')
Plug 'preservim/nerdtree'
Plug 'ryanoasis/vim-devicons'
Plug 'tiagofumo/vim-nerdtree-syntax-highlight'
call plug#end()
```

![Captura de pantalla de 2021-03-16 17-46-16](https://user-images.githubusercontent.com/66907184/111347613-a90b7100-867f-11eb-89bb-01180f760def.png)

**Comment by tiagofumo** [comment]
The icons are set by vim-devicons by default. This plugin only adds colors to icons. The screenshots on the README page are a result of my personal config at the time. To customize .css and .html icons the vim-devicon documentation says to add the code bellow to your .vimrc, but you need to add the unicode characters (which won't show on the browser).

```vim
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols = {} " needed
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['html'] = ''
let g:WebDevIconsUnicodeDecorateFileNodesExtensionSymbols['css'] = ''
```

In order to know which unicode characters you can use, try uploading your .otf file to [fontdrop](https://fontdrop.info/). It differs from file to file, but my icon for .html files is unicode E74F, and .css is E749. Check [this](https://en.wikipedia.org/wiki/Unicode_input#Hexadecimal_input) to find out how to input unicode characters for your OS.

Should look like this:
![image](https://user-images.githubusercontent.com/12556770/111378787-14097780-8681-11eb-94e0-3992564a6a35.png)
