### ISSUE TITLE
Showing Question Mark instead of icon

### ISSUE THREAD

**Issue by IshantSRam** [tiagofumo/vim-nerdtree-syntax-highlight#47]
showing "?" instead of icons
![Capture](https://user-images.githubusercontent.com/73593258/114819266-d5c7bb00-9dda-11eb-87fb-f81ac2be052b.PNG)

**Comment by kyleerin** [comment]
I see you're using devicons, did you set your terminal font to them? ie. Hack Nerd Font

**Comment by IshantSRam** [comment]
Yha I have downloaded Nerd Font, but what you mean by setting it in the terminal

**Comment by tiagofumo** [comment]
@IshantSRam the icons not showing up correctly is an issue with either the fontfile or the vim-devicons configuration. Try these steps:
1 - based on that print, try changing the order of the plugins in your .vimrc to see if it helps. I think it should be:
+Nerdtree
+Vim-devicons
+Vim-nerdtree-syntax-highlight
2- upload your nerdfonts font file to https://fontdrop.info/ and scroll down until you see if it includes all the icons it is supposed to. If it doesn't, you need another font file.
3- if it does include them, pick any icon's unicode number and try inserting it on the terminal. You can find on wikipedia how to insert unicode characters based on which OS you are using.

I am on my phone right now and because that I didn't try to format this message. Anyway, hope it helps

**Comment by kyleerin** [comment]
> Yha I have downloaded Nerd Font, but what you mean by setting it in the terminal

Like in the screenshot above, you have to tell the terminal application you're using to use Hack Nerd Font. Whether it's the macos Terminal app or iTerm2.
